name: Node.js CI

on: [push] 

jobs:
  export:
    name: Export on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    env:
      CI: true
      working-directory: ./SeeProfiler 
    
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, Build and Test
      run: |
        npm install
        npm test --if-present
      working-directory: ${{env.working-directory}}
    - name: Export App
      run: npm run export
      working-directory: ${{env.working-directory}}
    - name: Generate Artifact
      run: zip -r SeeProfiler Export/*
    # TODO - Create Release and upload the assets
