name: Node.js CI

on: [push] 

jobs:
  export:
    name: Export on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, Build and Test
      run: |
        npm install
        npm test --if-present
    - name: Export
      run: npm run export
    # TODO
    # grab here the data, zip it and publish a release ( only perform this operation on tag releases )   
      env:
        CI: true
